### ISSUE TITLE
Broken API contract

### ISSUE THREAD

**Issue by joshrendek** [emacs-lsp/lsp-go#1]
```Symbol's function definition is void: lsp-define-client```

Looks like it changed to https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L73-L120 and I'm unable to run the plugin.

**Comment by vibhavp** [comment]
Indeed, the API docs are incorrect at the moment. Will update them ASAP,
thanks

**Comment by casimir** [comment]
Any news on this?

**Comment by vibhavp** [comment]
Fixed in https://github.com/emacs-lsp/lsp-go/pull/2

**Comment by casimir** [comment]
Thanks!

**Comment by vibhavp** [comment]
Sorry for the late replies , I've been a bit busy with GSoC :/
