### ISSUE TITLE
Completion feature

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-go#12]
Thanks for the great work on `lsp-go`!

I noticed the recent commit 55601ec667df887fc1f9645e8bb8f29c774a175d, which adds `lsp-go--make-init-options` and some customizations. I don't understand why disable gocode completion feature (`lsp-go-gocode-completion-enabled`) by default, since `"-gocodecompletion"` is added to `lsp-go-language-server-flags` by default. Do you have any consideration to clarify? Thanks.

**Comment by bittopaz** [comment]
With the latest pr which include `lsp-go--make-init-options`, I think you can revert my pr: https://github.com/emacs-lsp/lsp-go/pull/11, and then enable `gocodecompletion` by default. @vibhavp

**Comment by seagle0128** [comment]
@thomasf You can use this setting `(setq lsp-go-gocode-completion-enabled t)`, without reverting the PR.

**Comment by thomasf** [comment]
I know, I checked the commit when I found this issue, thanks for replying anyway.

**Comment by seagle0128** [comment]
Welcome. I still think auto completion should be enabled by default. 
@bittopaz @vibhavp What do you think? I can make a PR for that.

**Comment by bittopaz** [comment]
I think so, and for me I also turn on the -diagnostics in my private config 😄

**Comment by seagle0128** [comment]
https://github.com/emacs-lsp/lsp-go/pull/13 has been merged. Close it.
